PI-coffeeBreak/frontend

- components.json
- index.html
- package-lock.json
- package.json
- src/App.jsx
- src/components/Box.jsx
- src/components/LayoutAuth.jsx
- src/components/Navbar.jsx
- src/components/ui/input-otp.tsx
- src/lib/utils.ts
- src/pages/Home.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/styles.css
- tsconfig.app.json
- tsconfig.json
- tsconfig.node.json
- vite.config.js
I did the steps at the registration page.
> Scrum 71 setting up register page

- src/App.jsx
- src/components/DropdownMenu.jsx
- src/components/Sidebar.jsx
- src/components/pagination.jsx
- src/pages/BaseConfiguration.jsx
- src/pages/Colors.jsx
- src/pages/Plugins.jsx
Plugins main page with all the available plugins, with pagination and search
> Scrum 99 event maker plugins main page

- src/pages/Alerts.jsx
> Scrum 121 home alerts page

- src/components/forms/ComposedText.jsx
> composed text done

- src/components/forms/Checkbox.jsx
> checkbox component done that suports toogle, single and multiple choice

- src/components/forms/Selector.jsx
> Selector done

- src/components/forms/ShortTextInput.jsx
- src/components/forms/TextInput.jsx
> text input and short text input components done

- src/components/ThemeCustomizer.jsx
- src/pages/Colors.jsx
This pull request introduces a new `ThemeCustomizer` component for customizing event themes, and integrates it into the `Colors` page. The most important changes include the creation of the `ThemeCustomizer` component, handling theme state and local storage, and updating the `Colors` page to use this new component.
* [`src/components/ThemeCustomizer.jsx`](diffhunk://#diff-2f0d054d6a6c5e8e9b05ed86d8cfa070f344ec08ba50e119493c758d78493d3dR1-R310): Added the `ThemeCustomizer` component, which allows users to customize event themes, save them to local storage, and preview changes in real-time. The component includes functionality for handling color changes, resetting to the original theme, and saving the theme.
* [`src/pages/Colors.jsx`](diffhunk://#diff-50de5f65bbe10a71d7c1f0e638063c4650d50ab4 …
> Scrum 95 app customization theme creation frontend

- src/pages/Plugins.jsx
- src/pages/Users.jsx
Refactor User page to use Pagination.jsx component
> Scrum 111 refactor home users to use pagination component

- src/App.jsx
- src/components/ThemeCustomizer.jsx
- src/consts.js
- src/contexts/ActivitiesContext.jsx
- src/contexts/PluginsContext.jsx
- src/contexts/ThemeContext.jsx
- src/contexts/UsersContext.jsx
- src/pages/Activities.jsx
- src/pages/Plugins.jsx
- src/pages/Schedule.jsx
- src/pages/Users.jsx
This pull request includes significant updates to the `App` component, the `ThemeCustomizer` component, and the introduction of new context providers for activities, plugins, and theme management. The most important changes include the addition of context providers, refactoring of the `ThemeCustomizer` component, and the addition of a new constant for maximum file size.
* Added `ActivitiesProvider` to manage activities and activity types, including fetching, updating, and organizing activities.
* Added `PluginsProvider` to manage plugins and their configurations, including fetching, loading, and unloading plugins.
* Added `ThemeProvider` to manage theme colors, including fetching and updating theme colors from the server.
* Refactored `ThemeCustomizer` component to use the `ThemeContext` …
> Scrum 141 refactor create axios context organizer app

- src/App.jsx
- src/components/Sidebar.jsx
This pull request includes changes to enhance the plugin management and routing in the application. The most important changes include modifying the routes and updating the sidebar to dynamically display enabled plugins.
Routing updates:
* [`src/App.jsx`](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661L48-R53): Changed the route path for plugins from `eventmaker/plugins` to `eventmaker/choose-plugins` and added a new nested route for `plugins/alerts`.
Sidebar enhancements:
* [`src/components/Sidebar.jsx`](diffhunk://#diff-0f7804eafe5f56106581a7149f16bcf316a4466155780612661ed7bffb305fb1R5-R20): Imported `usePlugins` from `PluginsContext` and added logic to filter and display enabled plugins dynamically in the sidebar. …
> refactor side bar

- .talismanrc
- package-lock.json
- package.json
- src/App.jsx
- src/components/CommonInputs.jsx
- src/components/ComponentConfigurations.jsx
- src/components/PluginSettingsModal.jsx
- src/components/SortableItem.jsx
- src/components/componentsMap.jsx
- src/contexts/ActivitiesContext.jsx
- src/contexts/ComponentsContext.jsx
- src/contexts/PagesContext.jsx
- src/contexts/PluginsContext.jsx
- src/contexts/ThemeContext.jsx
- src/contexts/UsersContext.jsx
- src/pages/HomeEditor.jsx
- src/pages/Schedule.jsx
This pull request introduces several new features and improvements to the project, including the addition of new dependencies, new components, and context providers, as well as enhancements to existing components.
* Added new dependencies `@dnd-kit/core` and `@dnd-kit/sortable` to `package.json` to support drag-and-drop functionalities.
* Introduced a new `componentConfigurations` object in `src/components/ComponentConfigurations.jsx` to define configurations for various components like `Heading`, `Title`, `Text`, `Button`, and `Image`.
* Added a new `SortableItem` component in `src/components/SortableItem.jsx` to manage sortable items with drag-and-drop and property editing capabilities.
* Added new context providers (`PagesProvider`, `ComponentsProvider`) and integrated them into the …
> Scrum 158 frontend homepage customization page

- src/components/event_maker/pages/DynamicComponentConfiguration.jsx
- src/components/event_maker/pages/components/Image.jsx
- src/consts.js
- src/contexts/PagesContext.jsx
- src/keycloak.js
- vite.config.js
This PR, not only introduces the logic to upload Images in Components on Page Editor, but also change vite.config.js to correctly import .env variables
> Add image upload to Page Editor Components

- src/App.jsx
- src/components/ColorSelector.jsx
- src/components/ColorThemeLayout.jsx
- src/components/LayoutAuth.jsx
- src/components/event_maker/pages/DynamicComponentConfiguration.jsx
- src/components/event_maker/pages/PageHeader.jsx
- src/components/event_maker/pages/components/Image.jsx
- src/components/event_maker/pages/components/Text.jsx
- src/components/event_maker/pages/components/Title.jsx
- src/components/event_maker/pages/components/utils.js
- src/components/forms/MediaInput.jsx
- src/contexts/ColorThemeContext.jsx
- src/hooks/useSections.js
- src/pages/page_editor/CreatePage.jsx
- src/pages/page_editor/EditPage.jsx
Media upload works (and colors)
This pull request introduces a new color theme management system and refactors several components to integrate with this new system. The most important changes include adding a `ColorThemeProvider` to the application, creating a `ColorThemeLayout` component, updating the `ColorSelector` component, and modifying various components to use the new color theme context.
* [`src/App.jsx`](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R33-R38): Added `ColorThemeProvider` to wrap the application, ensuring that the color theme context is available throughout the app. [[1]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R33-R38) [[2]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5 …
> Scrum 192 fix page editor text colors media upload

- src/contexts/MenuContext.jsx
> Add authorization header on MenuContext to fix 401 errors

- src/pages/Plugins.jsx
Improve IHC Score by adding more responsivity to plugins management page
> Show loading spinner while enabling/disabling a plugin

- .env
- src/App.jsx
- src/components/event_maker/pages/DynamicComponentConfiguration.jsx
- src/contexts/AlertsContext.jsx
- src/pages/Alerts.jsx
- src/pages/EventSetup.jsx
This pull request introduces a new alert system plugin and includes several changes to support its functionality. The main updates involve adding new environment variables, creating a new `AlertsContext` for managing alerts, and integrating this context into the application. Additionally, there are updates to the `Alerts` page to utilize the new alert functionalities.
* Added new environment variables for API keys, Keycloak configuration, and base URLs in `.env`.
* Added `AlertsProvider` to `src/App.jsx` to provide alert functionalities throughout the application. [[1]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R34) [[2]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R56) …
> Scrum 174 send alerts integration

- src/components/Activity.jsx
- src/components/activities/ActivityFilters.jsx
- src/components/activities/ActivityList.jsx
- src/components/activities/CreateActivityCards.jsx
- src/components/activities/ExcelImportModal.jsx
- src/components/activities/NewSessionModal.jsx
- src/components/common/Modal.jsx
- src/contexts/ActivitiesContext.jsx
- src/hooks/useForm.js
- src/pages/Activities.jsx
- src/pages/Schedule.jsx
This pull request includes several significant changes to the `src/components` and `src/contexts` directories, focusing on adding new features, improving user experience, and enhancing code maintainability. The most important changes include the addition of delete functionality for activities, the introduction of activity filters, and the implementation of an Excel import modal for bulk activity creation.
* **Delete Activity Functionality:**
- [`src/components/Activity.jsx`](diffhunk://#diff-5f2374b6b2744b33dfec233b1e42af302e27d773b59a465c2c5aa1355976b505L1-R25): Added a delete button with a trash icon to allow users to delete activities. The button triggers the `onDelete` function passed as a prop.
- [`src/components/activities/ActivityList.jsx`](diffhunk://#diff-c6bec5255c613100de8c13f97 …
> Scrum 197 improve activity management

- src/App.jsx
- src/components/Activity.jsx
- src/components/activities/ActivityFilters.jsx
- src/components/activities/CreateActivityCards.jsx
- src/components/activities/ExcelImportModal.jsx
- src/components/activities/NewSessionModal.jsx
- src/components/activities/NewSessionTypeModal.jsx
- src/components/common/Modal.jsx
- src/components/layout/Layout.jsx
- src/components/layout/LayoutAuth.jsx
- src/components/layout/LayoutInstantiate.jsx
- src/consts.js
- src/contexts/ActivitiesContext.jsx
- src/pages/Activities.jsx
This pull request includes several changes aimed at refactoring the codebase, improving the structure of components, and enhancing the user interface. The most important changes include restructuring imports, removing unused components, adding new functionalities, and cleaning up code comments.
* [`src/App.jsx`](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661L6-R8): Restructured imports to organize components under the `components/layout` directory and removed the unused `SpeakerManagement` component. [[1]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661L6-R8) [[2]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661L24-L27) [[3]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c3 …
> Scrum 217 refactor and clean activities

- src/components/event_maker/pages/DynamicComponentConfiguration.jsx
- src/components/event_maker/pages/PageContent.jsx
- src/components/event_maker/pages/SortableItemLayout.jsx
- src/pages/page_editor/CreatePage.jsx
- src/pages/page_editor/EditPage.jsx
This pull request introduces several enhancements and fixes to improve the drag-and-drop functionality, optimize performance, and refine the user interface in the event maker pages. Key changes include adding advanced drag-and-drop configurations, optimizing rendering with memoization, and improving the styling and behavior of sortable items.
* Added support for `PointerSensor` and `KeyboardSensor` with activation constraints and keyboard coordinate handling in `PageContent`. Introduced modifiers such as `restrictToVerticalAxis` and `restrictToParentElement` to restrict drag movements. (`src/components/event_maker/pages/PageContent.jsx`, [[1]](diffhunk://#diff-3b3f08150507ac034f2daca977b810ed74175dca7355166e34f3992ff89b3613L1-R10) …
> Scrum 216 fix dnd problems in page editor page

- src/contexts/AlertsContext.jsx
A small fix to remove an wrong parameter that has been sent to alert post endpoint.
> Fix wrong endpoint call on alert provider

- .talismanrc
- package-lock.json
- package.json
- src/components/event_maker/pages/components/Location.jsx
- src/components/event_maker/pages/components/index.js
This pull request introduces a new `Location` component for displaying event location details on a map, utilizing the `react-leaflet` library. It also updates the component index file to include the new component. Below are the key changes:
* **`src/components/event_maker/pages/components/Location.jsx`**: Added a new `Location` component that integrates a map using `react-leaflet`. It includes features like displaying a marker, copying the address, and opening directions in Google Maps. The component also supports restricted access to location details for authenticated users.
* **`package.json`**: Added the `react-leaflet` library (version `^5.0.0`) to enable map functionality in the `Location` component.
* **`src/components/event_maker/pages/components/index.js`**: Updated the component …
> Scrum 177 component with event location link

- src/components/event_maker/pages/PageContent.jsx
This pull request simplifies the `PageContent` component in `PageContent.jsx` by refactoring how event handlers are passed to child components. 
Code simplification:
* [`src/components/event_maker/pages/PageContent.jsx`](diffhunk://#diff-3b3f08150507ac034f2daca977b810ed74175dca7355166e34f3992ff89b3613L55-R56): Updated the `onComponentTypeChange` and `onComponentPropsChange` props to pass the original functions directly instead of wrapping them in anonymous functions. This reduces redundancy and improves readability.
> fix functions passed to dynamicconfiguration

- src/pages/page_editor/CreatePage.jsx
- src/pages/page_editor/EditPage.jsx
- src/utils/pageUtils.js
This pull request enhances the `CreatePage` and `EditPage` components to ensure that all components include default schema properties when saving or updating a page. It introduces a utility to populate component properties with schema defaults and updates the logic for handling component data in both components.
* `src/pages/page_editor/CreatePage.jsx`:
- Added `getComponentSchema` to retrieve schema details for components.
- Implemented logic to populate component properties with schema defaults when saving a page. This ensures all required properties are included, even if they weren't explicitly set.
- Added a debug log to display the components being saved.
* `src/pages/page_editor/EditPage.jsx`:
- Added `getComponentSchema` for schema retrieval, mirroring the changes in `CreatePage`. …
> change update and create page handlers

- src/contexts/PagesContext.jsx
This pull request includes a small change to the `PagesProvider` component in `src/contexts/PagesContext.jsx`. The change updates the API endpoint from `/pages` to `/pages/all` to fetch all pages.
> modified get pages link

- src/App.jsx
- src/components/DashboardCard.jsx
- src/components/DropdownMenu.jsx
- src/components/Sidebar.jsx
- src/pages/EventMaker.jsx
- src/pages/Instantiate.jsx
- src/pages/Management.jsx
This pull request introduces significant updates to the application's navigation structure, component styling, and functionality. Key changes include the addition of a "Management" section in the routing and sidebar, enhanced color handling for `DashboardCard`, improved accessibility and functionality for `DropdownMenu`, and various updates to the `Sidebar` component for better navigation and user experience.
* Added a new "Management" section to the application routing, with routes for "Users," "Sessions," and "Alerts" under the `management` path. Updated the `App.jsx` file to reflect these changes. (`src/App.jsx`, [[1]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R27) [[2]](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c …
> Scrum 230 fix sidebar frontend

- src/components/Navbar.jsx
- src/pages/Home.jsx
This pull request makes several updates to the `Navbar` and `Home` components to improve UI consistency, simplify the layout, and update links. The most significant changes include adjustments to padding and margins, removal of the footer and newsletter section from the homepage, and updating the "Learn more" link to an external URL.
* Modified padding in the `Home` component to reduce vertical spacing for a more compact layout. (`src/pages/Home.jsx`, [[1]](diffhunk://#diff-3f516fbdeb9a7ec0382eddb852845968f9cdaa1cff026ac0ce8fdf1fd351cc17L60-R60) [[2]](diffhunk://#diff-3f516fbdeb9a7ec0382eddb852845968f9cdaa1cff026ac0ce8fdf1fd351cc17L85-R92)
* Updated the "Learn more" link in the `Home` component to point to an external GitHub Pages URL instead of the internal `/about` route. …
> clean trash links

- src/pages/Home.jsx
This pull request updates the `Home` component in `src/pages/Home.jsx` to improve the logic for checking event data by ensuring the check is performed only once after authentication is initialized. The changes include adding a new state variable and adjusting the dependency array for the `useEffect` hook.
* Added a new state variable `hasCheckedEvent` to track whether the event check has already been performed, ensuring the logic runs only once after authentication is initialized. (`src/pages/Home.jsx`, [src/pages/Home.jsxR12-R20](diffhunk://#diff-3f516fbdeb9a7ec0382eddb852845968f9cdaa1cff026ac0ce8fdf1fd351cc17R12-R20))
* Updated the `useEffect` dependency array to include `hasCheckedEvent`, preventing unnecessary re-execution of the event-checking logic. (`src/pages/Home.jsx`, …
> avoid multiple context calls

- src/components/Activity.jsx
- src/keycloak.js
- src/pages/Activities.jsx
- src/utils/axiosWithAuth.js
Fix images on activities
Fix token that was not refreshing sometimes
This pull request introduces several improvements and fixes across multiple components, focusing on enhancing media handling, token management, and API request behavior. The changes streamline functionality, improve error handling, and ensure a better user experience.
* [`src/components/Activity.jsx`](diffhunk://#diff-5f2374b6b2744b33dfec233b1e42af302e27d773b59a465c2c5aa1355976b505R4-R22): Added logic to dynamically resolve `image` URLs using the `MediaContext`. If the `image` is not a valid URL, it is resolved via `getMediaUrl`. Additionally, an error handler was added to the `<img>` tag to display a fallback UI when the image fails to load. [[1]](diffhunk://#diff-5f2374b6b2744b33dfec233b1e42af302e27d773b59a465c2c5aa1355 …
> Fix activities images & auth token refresh

- src/pages/page_editor/CreatePage.jsx
An old commit have, accidentally, changed the name of a method to handle page creation. This, and some other changes in `CreatePage.jsx` were done.
> Fix error with create page

- src/components/event_maker/pages/DynamicComponentConfiguration.jsx
Add support for N inputs by creating a crud input (lists)
Any labels are now referenced by the component class, instead of being hardcoded
> Add list input support & fix Any labels

- src/components/Sidebar.jsx
This pull request introduces a minor improvement to the `Sidebar` component by refining the logic for determining enabled plugins.
* [`src/components/Sidebar.jsx`](diffhunk://#diff-0f7804eafe5f56106581a7149f16bcf316a4466155780612661ed7bffb305fb1R86): Updated the `enabledPlugins` logic to include only plugins that have a `config_page` property in addition to being loaded.
> filter config page attribute from plugins

- src/App.jsx
- src/pages/FloorPlans.jsx
This pull request adds a new `FloorPlans` feature to the application by integrating it into the routing system and importing the corresponding component.
* [`src/App.jsx`](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R24): Imported the `FloorPlans` component from `./pages/FloorPlans.jsx`.
* [`src/App.jsx`](diffhunk://#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661R63): Added a new route for the `FloorPlans` feature under the path `floor-plan-plugin`.
> Floor Plan Management Page

- src/App.jsx
- src/components/Sidebar.jsx
- src/pages/Management.jsx
This pull request removes the "Alerts" feature from the application. The changes span multiple files, ensuring that all references to "Alerts" are removed from the user interface and navigation.
* **Route Removal**: The "alerts" route was removed from the main application router in `src/App.jsx`.
* **Sidebar Update**: The "Alerts" link was removed from the sidebar navigation in `src/components/Sidebar.jsx`.
* **Management Page Update**: The "Alerts" card was removed from the Management page in `src/pages/Management.jsx`.
> remove alert link in sidebar

- src/components/plugins/config/Toggle.jsx
- src/contexts/PluginsContext.jsx
- src/pages/Plugins.jsx
This pull request introduces several changes to improve the handling of plugin data and simplify the codebase. The most significant updates include the removal of the `formatted_name` property and its associated formatting logic, adjustments to plugin state management, and the addition of a hidden input field to the `Toggle` component for better form handling.
* Removed the `formatPluginName` function and the `formatted_name` property from plugin objects, simplifying the plugin data structure. This affects multiple files, including `PluginsContext.jsx` and `Plugins.jsx`. (`[[1]](diffhunk://#diff-6f369b89a65f70545a91fc0771fb2a561e43b3ec093b819f6a66ae5ac65162f4L9-L17)`, `[[2]](diffhunk://#diff-6f369b89a65f70545a91fc0771fb2a561e43b3ec093b819f6a66ae5ac65162f4L33-R25)`, …
> Fix toggle and name handling

- src/components/activities/ActivityFilters.jsx
- src/components/activities/NewSessionTypeModal.jsx
> Scrum 244 color on activity type

- src/components/common/Sidebar.jsx
- src/components/plugins/PluginSettingsModal.jsx
This pull request includes a small change to the `Sidebar` component. The change updates the `label` property for plugins in the sidebar to use `plugin.name` instead of `plugin.formatted_name` for consistency.
> fix names inn sidebar too

- src/components/event_maker/pages/components/FeedbackForm.jsx
- src/components/event_maker/pages/components/index.js
- src/locales/en/translation.json
- src/locales/pt-BR/translation.json
- src/locales/pt-PT/translation.json
This pull request introduces a new `FeedbackForm` component to collect user feedback, integrates it into the existing component system, and updates localization files to support multilingual feedback content. Below are the key changes grouped by theme:
* Added a `FeedbackForm` component in `FeedbackForm.jsx`, which includes a star rating system, an optional comment box, and a submit button. It uses default fallback data and supports localization via the `react-i18next` library.
* Imported `FeedbackFormComponent` into `index.js` and registered it in the `Components` object and `componentList` array, making it available for use in the application. [[1]](diffhunk://#diff-0484e26426e16bd204e3906784e9dfcdac0960d16cb3217888d95e0b6d694a19R8) …
> Feedback component done.

- src/components/common/CreateCard.jsx
- src/components/common/DropdownMenu.jsx
- src/components/common/Sidebar.jsx
- src/locales/en/translation.json
- src/locales/pt-BR/translation.json
- src/pages/Activities.jsx
- src/pages/EventSetup.jsx
- src/pages/Instantiate.jsx
- src/pages/Users.jsx
- src/styles.css
This pull request introduces several updates across components, styles, and localization files to enhance the user interface, improve accessibility, and refine functionality. The changes include adjustments to component layouts, styling updates for consistency, and modifications to localization strings. Below is a summary of the most significant changes, grouped by theme.
* Updated the `CreateCard` component to switch from a column layout to a row layout, added spacing between elements, and adjusted icon sizes for better responsiveness (`src/components/common/CreateCard.jsx`).
* Modified the `DropdownMenu` component to use rounded corners for buttons and menu items, improving the visual design (`src/components/common/DropdownMenu.jsx`). …
> Refresh after event creation

- src/components/common/DropdownMenu.jsx
This pull request updates the `DropdownMenu` component to improve its responsiveness and usability. The most significant changes include adjusting the maximum height calculation for the dropdown and enabling vertical scrolling for better handling of long lists.
Improvements to `DropdownMenu`:
* Updated the `open` state styling to calculate the maximum height dynamically based on the viewport height (`max-h-[calc(100vh-400px)]`) instead of using a fixed value (`max-h-96`). This ensures the dropdown adapts better to different screen sizes.
* Added `overflow-y-auto` to the `<ul>` element to enable vertical scrolling, improving usability when the dropdown contains many items.
> fix dropdown so all the plugins are visible

- src/components/activities/ExcelImportModal.jsx
- src/components/activities/NewSessionModal.jsx
- src/pages/Activities.jsx
- src/pages/plugins/Schedule.jsx
This pull request introduces several updates to streamline session and activity data handling, improve UI consistency, and integrate event-specific constraints. The most significant changes involve refactoring data structures, simplifying form fields, and adding contextual event restrictions in the calendar component.
* Replaced the `start_time` field with `date` across components and updated related logic to reflect this change. (`src/components/activities/ExcelImportModal.jsx`, `src/pages/Activities.jsx`) [[1]](diffhunk://#diff-bdfd8e564893d9ac86863f617fee37f4c26e1158e41c093efa33050659ef0fb6L17-L21) [[2]](diffhunk://#diff-bdfd8e564893d9ac86863f617fee37f4c26e1158e41c093efa33050659ef0fb6L166-L170) [[3]](diffhunk://#diff-1e9fb9997bb69d6eac9ac4d0a6a5cf55023f3a745a7cad95f17c70f122e15ee7L91-L9 …
> Scrum 270 calendar allows to insert activities outside event time range

- src/components/event_maker/pages/components/FloorPlan.jsx
- src/components/event_maker/pages/components/index.js
This pull request introduces a new `FloorPlanComponent` to the event maker application and integrates it into the component system. The changes include the creation of the new component, updates to the component registry, and adjustments to the component list for UI selection.
* [`src/components/event_maker/pages/components/FloorPlan.jsx`](diffhunk://#diff-07027714f683f3c9f3c13b0e0522234220444478676b8b3378fc8be49bbc50e4R1-R197): Added the `FloorPlanComponent`, which dynamically fetches and displays floor plans, supports fallback data, and includes a selector for multiple floor plans. Prop types were defined for better validation.
* `src/components/event_maker/pages/components/index.js`:
- Imported the new `FloorPlanComponent` into the component registry.
- Added `FloorPlanComponent` to …
> Component preview

- package.json
- vite.config.js
Because of build size, default nodejs 2GB limit is too small, throwing an error.
The value was increased to 4GB
> Increase build memory limits

- src/pages/plugins/SpeakerManagement.jsx
This pull request makes several updates to the `SpeakerManagement` component, focusing on improving the data model, enhancing the user interface, and removing unnecessary console logs. The primary changes include adding a `role` field for speakers, refactoring the form and API payloads to include this field, and cleaning up the code by eliminating debug logs.
* Added a `role` field to the speaker data model, updated the form's state initialization, and modified API payloads for creating and updating speakers to include `role`. (`[[1]](diffhunk://#diff-33a66dc431aeedb8bbaa60a1098228b6c68688f8baebba24a779ff2e8273ed33L64-R58)`, `[[2]](diffhunk://#diff-33a66dc431aeedb8bbaa60a1098228b6c68688f8baebba24a779ff2e8273ed33L146-L154)`, `[[3]](diffhunk://#diff-33a66dc431aeedb8bbaa60a1098228b6c68688f8ba …
> Scrum 273 add role to speakers in plugin frontend form and app component

- src/App.jsx
- src/locales/en/translation.json
- src/locales/pt-BR/translation.json
- src/locales/pt-PT/translation.json
- src/pages/plugins/ActivitiesFeedback.jsx
This pull request introduces a new "Activities Feedback" feature to the application, enabling users to view and filter feedback on activities. The changes include adding a new page component, updating routes, and extending localization files for multiple languages.
* **New Component**: Added the `ActivitiesFeedback` component to display activity feedback with filtering and pagination functionality. It includes features such as fetching feedback, calculating average ratings, filtering by rating and user type, and displaying feedback in a paginated format. (`src/pages/plugins/ActivitiesFeedback.jsx`)
* **Routing Update**: Added a new route `activities-feedback-plugin` to render the `ActivitiesFeedback` component. (`src/App.jsx`)
* **English Translations**: Added translations for the …
> Add feedback page

- src/components/event_maker/ThemeCustomizer.jsx
This pull request refactors the `ThemeCustomizer` component in `ThemeCustomizer.jsx` to improve accessibility, user experience, and code maintainability. The most notable changes include restructuring the UI layout, enhancing accessibility attributes, and updating the styling logic for better visual consistency.
* Updated the layout of the color picker elements to use a more centralized and vertically aligned design, making the interface more user-friendly.
* Added an `aria-label` attribute to the color input elements for better screen reader support and accessibility.
* Adjusted the `tabIndex` and `zIndex` properties of the color input for improved keyboard navigation and layering.
* Refactored the color preview and label styling to ensure better alignment and consistent spacing. Added …
> improve color page looks

- src/pages/page_editor/EditPage.jsx
This pull request updates the navigation behavior in the `EditPage` component to point to a more appropriate route.
* **Navigation update in `EditPage`:**
- The `onBack` function in the `PageActions` component now navigates to `/instantiate/application/pages` instead of `/instantiate/eventmaker/pages`. (`src/pages/page_editor/EditPage.jsx`, [src/pages/page_editor/EditPage.jsxL236-R236](diffhunk://#diff-d4dcfd0765acc11dd6fbd1db775284b3a0187de2e9153ee4db68d965519c1ef0L236-R236))
> change url from navigate

- src/components/event_maker/pages/components/Sponsors.jsx
This pull request improves the robustness of the `SponsorsComponent` in the `src/components/event_maker/pages/components/Sponsors.jsx` file by adding checks to ensure the `sponsors` and `levels` props are valid arrays before accessing their length.
Enhancements to input validation:
* Updated the `displaySponsors` logic to check if `sponsors` is an array before verifying its length, preventing potential runtime errors when `sponsors` is not an array.
* Updated the `displayLevels` logic to check if `levels` is an array before verifying its length, ensuring similar protection against invalid input.
> solve the problem

- src/PrivateRoute.js
- src/components/common/Pagination.jsx
- src/components/event_maker/pages/DynamicComponentConfiguration.jsx
- src/contexts/Provider.jsx
- src/contexts/UsersContext.jsx
- src/styles.css
This pull request introduces PropTypes validation across multiple components to ensure proper type checking and improve code robustness. Additionally, some minor cleanups were made in the `UsersContext` file, and a plugin configuration was removed from the `styles.css` file. Below is a breakdown of the most important changes:
* [`src/PrivateRoute.js`](diffhunk://#diff-363b6ac79a052cb1119fabdc51f1c4cc8208e0dbe7056aa56187b6601f790db5R2-R13): Added PropTypes validation to enforce that `children` is a required node.
* [`src/components/common/Pagination.jsx`](diffhunk://#diff-98bf60d08c2e4ead723e32c1d8f20caa9f974183fe9d559141fde0d6f34f9357R2): Added PropTypes validation for `currentPage`, `totalPages`, and `onPageChange` props. [[1]](diffhunk://#diff-98bf60d08c2e4ead723e32c1d8f20caa9f974183fe9d …
> add proptypes

- src/styles.css
This pull request updates the `src/styles.css` file to introduce a custom theme using the `daisyui/theme` plugin and makes minor formatting adjustments. Below are the key changes:
* Added a new custom theme named "mytheme" using the `daisyui/theme` plugin with specific properties such as `default: true`, `prefersdark: false`, and `color-scheme: light`. This enhances the ability to manage theme settings centrally.
* Removed unnecessary blank lines to improve code readability and maintain a cleaner structure.
> rollback styles

- .talismanrc
- index.html
This pull request includes updates to improve security and configuration management. The most notable changes involve adding integrity attributes to external scripts in `index.html` and updating the `.talismanrc` file to include a new file for checksum validation.
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L11-R11): Added an `integrity` attribute to the `particles.min.js` script to ensure the script's content is not tampered with during loading.
* [`.talismanrc`](diffhunk://#diff-efcd051724f24a743f7e1d572b337b61f6a1137ea138173c59346095eedd972aR8-R9): Updated the `fileignoreconfig` section to include `index.html` with its checksum for validation, ensuring it is monitored for changes.
> add integrity to scripts

- .github/workflows/push-ghcr.yml
Add arm64 support on docker images
> Add arm64 support

- .github/workflows/push-ghcr.yml
> Fix push workflow

- src/components/activities/CreateActivityTypeModal.jsx
- src/components/alerts/AlertFilters.jsx
- src/contexts/ActivitiesContext.jsx
- src/locales/en/translation.json
- src/pages/plugins/ActivitiesFeedback.jsx
- src/pages/plugins/Alerts.jsx
- src/pages/plugins/Schedule.jsx
- src/pages/plugins/Sponsors.jsx
This pull request introduces several updates across multiple files to enhance activity management, improve user feedback, and refine UI components. Key changes include adding support for editing and deleting activity types, improving the feedback system for activities, and introducing a confirmation modal for removing activities from the schedule. Additionally, various UI elements have been updated for consistency and better user experience.
* Added `deleteActivityType` functionality in `ActivitiesContext` to allow deletion of activity types, updating the state accordingly. (`src/contexts/ActivitiesContext.jsx`, [[1]](diffhunk://#diff-673f5c56e5124830d184dbf1d59cd618ee5ec0c08997800de9ac1a7a95297edbR215-R235) [[2]](diffhunk://#diff-673f5c56e5124830d184dbf1d59cd618ee5ec0c08997800de9ac1a7a952 …
> Scrum 308 refactor components

- src/pages/plugins/SpeakerManagement.jsx
This pull request enhances the `SpeakerManagement` component by adding support for social media links, including validation, UI updates, and data handling. The changes improve the user experience by allowing speakers to include their social media profiles and ensuring these inputs are properly validated and displayed.
* Added new fields (`linkedin`, `facebook`, `instagram`, `youtube`) to the `formData` state and the `speakerData` payload to store social media links. These fields are also included in the speaker creation and export processes. [[1]](diffhunk://#diff-33a66dc431aeedb8bbaa60a1098228b6c68688f8baebba24a779ff2e8273ed33R36-R39) [[2]](diffhunk://#diff-33a66dc431aeedb8bbaa60a1098228b6c68688f8baebba24a779ff2e8273ed33R138-R141) …
> add socials to speaker

- src/pages/PagesList.jsx
- src/pages/page_editor/CreatePage.jsx
menu option creation isn't using baseUrl constant, throwing a 405 error
> Fix menu option creation not using baseUrl const

- src/pages/PagesList.jsx
- src/pages/page_editor/CreatePage.jsx
See: Hotfix/page menu option not being created #124
> Hotfix/page menu option not being created [Dev]

- src/components/common/Sidebar.jsx
- src/locales/en/translation.json
- src/locales/pt-BR/translation.json
- src/locales/pt-PT/translation.json
- src/pages/plugins/FloorPlans.jsx
- src/pages/plugins/Schedule.jsx
This pull request introduces several updates across multiple files, focusing on UI enhancements, localization improvements, and minor bug fixes. Key changes include the addition of theme-based styling in the `Sidebar` component, updates to translation files for better localization support in `en`, `pt-BR`, and `pt-PT`, and small bug fixes in various components to improve functionality and maintainability.
* [`src/components/common/Sidebar.jsx`](diffhunk://#diff-6642d86e467801e7490252b0b21690ff64f8f0c09bbdc268d6e88b31a094c72cR29): Integrated theme-based styling by importing `useTheme` and applying `theme.accent` to the background color of specific elements. [[1]](diffhunk://#diff-6642d86e467801e7490252b0b21690ff64f8f0c09bbdc268d6e88b31a094c72cR29) …
> Add missing translations

- src/components/activities/CreateActivityModal.jsx
- src/components/activities/EditActivityModal.jsx
- src/pages/plugins/Schedule.jsx
- src/utils/date.js
This pull request introduces utilities for handling date conversions between local and UTC formats and integrates them across multiple components to standardize date handling. The changes improve consistency and accuracy when managing date inputs and outputs in the application.
* Added three new utility functions in `src/utils/date.js`:
- [`toUTCISOString`](diffhunk://#diff-cd848e15ae36f0d06d38dd84247b7a375ab54c5d432d38acaf8e77009e586450R1-R33): Converts a local date string to a UTC ISO string.
- [`utcToLocalDatetimeLocal`](diffhunk://#diff-cd848e15ae36f0d06d38dd84247b7a375ab54c5d432d38acaf8e77009e586450R1-R33): Converts a UTC ISO string to a local `datetime-local` string.
- [`localDatetimeLocalToUTC`](diffhunk://#diff-cd848e15ae36f0d06d38dd84247b7a375ab54c5d432d38acaf8e77009e586450R1-R33) …
> date utils

- src/pages/plugins/Schedule.jsx
This pull request refactors and enhances the `DragDropCalendar` component in `src/pages/plugins/Schedule.jsx`. Key improvements include better handling of date conversions, new event handlers for resizing and moving activities, and updates to the calendar's configuration for improved usability. Additionally, unused imports and redundant code were removed to clean up the file.
* Added `utcToLocalDatetimeLocal` utility function for converting UTC to local datetime, ensuring proper date handling across the calendar. (`[[1]](diffhunk://#diff-567fc28688e07fdc6951e38da0565b2f197546cef89d6902e12079ee01bf5925L10-R13)`, `[[2]](diffhunk://#diff-567fc28688e07fdc6951e38da0565b2f197546cef89d6902e12079ee01bf5925L400-R390)`)
* Introduced new event handlers: `handleEventResize` for resizing activities …
> fix event times when dragging

- src/components/activities/ActivityList.jsx
max-h-screen was limiting displayed activities
> remove height limit on activity list

- src/pages/plugins/SpeakerManagement.jsx
This pull request includes a small change to the `SpeakerManagement` component. The change removes an unnecessary trailing slash from the API endpoint URL in the `axiosWithAuth` `patch` request.
> fix complete
